# Generated by Django 2.0.5 on 2018-05-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0002_auto_20180526_1011")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_owner",
            field=models.BooleanField(default=False),
        )
    ]
