# Generated by Django 2.0.5 on 2018-05-31 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0004_profile_stripe_id")]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="is_owner", new_name="is_admin"
        )
    ]
