# Generated by Django 2.0.6 on 2018-06-03 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_photo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo_url',
            new_name='photo',
        ),
    ]
