# Generated by Django 2.0.7 on 2018-07-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0007_auto_20180603_1804")]

    operations = [
        migrations.AddField(
            model_name="company",
            name="routeId",
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        )
    ]
