# Generated by Django 2.0.7 on 2018-07-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0008_company_routeid")]

    operations = [
        migrations.RenameField(
            model_name="company", old_name="routeId", new_name="route_id"
        )
    ]
