# Generated by Django 2.0.7 on 2018-07-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0009_auto_20180721_1344")]

    operations = [
        migrations.RenameField(
            model_name="company", old_name="route_id", new_name="route"
        )
    ]
