# Generated by Django 2.0.7 on 2018-07-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0010_auto_20180721_1351")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(default="static/images/profile.svg", upload_to=""),
        )
    ]
