# Generated by Django 2.0.7 on 2018-07-25 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_company_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='photo',
            new_name='logo',
        ),
    ]
