# Generated by Django 2.0.7 on 2018-07-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0015_auto_20180726_2016")]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("body", models.TextField(blank=True, max_length=600, null=True)),
            ],
        )
    ]
