# Generated by Django 2.0.7 on 2018-07-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0017_resource_company")]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="body",
            field=models.TextField(blank=True, null=True),
        )
    ]
