# Generated by Django 2.0.7 on 2018-07-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0019_post")]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.CharField(default="slug", max_length=300),
            preserve_default=False,
        )
    ]
