# Generated by Django 2.0.7 on 2018-07-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0020_post_slug")]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(default="default"),
            preserve_default=False,
        )
    ]
