# Generated by Django 2.0.7 on 2018-07-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0021_auto_20180731_2137")]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
        )
    ]
