# Generated by Django 2.0.7 on 2018-07-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0022_subscriber")]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        )
    ]
