# Generated by Django 2.0.7 on 2018-07-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0023_auto_20180731_2243")]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="email",
            field=models.EmailField(max_length=254),
        )
    ]
