# Generated by Django 2.0.7 on 2018-08-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_analytic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slack',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
