# Generated by Django 2.0.7 on 2018-08-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0026_auto_20180801_1229")]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="slug",
            field=models.CharField(default="default-resource-slug", max_length=300),
            preserve_default=False,
        )
    ]
