# Generated by Django 2.1 on 2018-08-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0028_auto_20180801_1400")]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="source",
            field=models.CharField(blank=True, max_length=300, null=True),
        )
    ]
