# Generated by Django 2.1 on 2018-08-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0031_auto_20180811_0023")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(blank=True, max_length=300, null=True),
        )
    ]
