# Generated by Django 2.1 on 2018-08-23 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0037_auto_20180823_1709")]

    operations = [
        migrations.AlterModelOptions(
            name="answer", options={"ordering": ("created_at",)}
        ),
        migrations.AlterModelOptions(name="post", options={"ordering": ("-date",)}),
        migrations.AlterModelOptions(
            name="question", options={"ordering": ("-updated_at",)}
        ),
        migrations.AlterModelOptions(name="resource", options={"ordering": ("title",)}),
        migrations.RemoveField(model_name="tag", name="resource"),
    ]
