# Generated by Django 2.1 on 2018-08-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0038_auto_20180823_2031")]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="resources",
            field=models.ManyToManyField(to="main.Resource"),
        )
    ]
