# Generated by Django 2.1 on 2018-08-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0039_tag_resources")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="timezone",
            field=models.CharField(blank=True, max_length=300, null=True),
        )
    ]
