# Generated by Django 2.1 on 2018-08-24 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0040_profile_timezone")]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="timezone", new_name="time_zone"
        )
    ]
