# Generated by Django 2.1 on 2018-08-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0043_auto_20180826_0050")]

    operations = [migrations.RemoveField(model_name="tag", name="resources")]
