# Generated by Django 2.1 on 2018-08-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0045_auto_20180827_1324")]

    operations = [
        migrations.AlterField(
            model_name="tagresource",
            name="is_pinned",
            field=models.BooleanField(default=False),
        )
    ]
