# Generated by Django 2.1 on 2018-08-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0046_auto_20180827_1522")]

    operations = [migrations.RemoveField(model_name="tagresource", name="is_pinned")]
