# Generated by Django 2.1 on 2018-09-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0049_company_invite_data")]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                default="/static/images/company-profile.png",
                max_length=300,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                default="/static/images/profile.png", max_length=300, upload_to=""
            ),
        ),
    ]
