# Generated by Django 2.1 on 2018-09-12 21:03

from django.db import migrations


def change_profile_photo_default(apps, schema_editor):
    Profile = apps.get_model("main", "Profile")
    for profile in Profile.objects.all():
        if profile.photo == "/static/images/person.svg":
            profile.photo = "/static/images/profile.png"
            profile.save()


class Migration(migrations.Migration):

    dependencies = [("main", "0050_auto_20180912_2022")]

    operations = [migrations.RunPython(change_profile_photo_default)]
