# Generated by Django 2.1 on 2018-09-12 21:28

from django.db import migrations


def change_company_profile_logo_default(apps, schema_editor):
    Company = apps.get_model("main", "Company")
    for company in Company.objects.all():
        if company.logo == "/static/images/logo.svg":
            company.logo = "/static/images/company-profile.png"
            company.save()


class Migration(migrations.Migration):

    dependencies = [("main", "0051_auto_20180912_2103")]

    operations = [migrations.RunPython(change_company_profile_logo_default)]
