# Generated by Django 2.1 on 2018-09-15 05:52

from django.db import migrations


def set_all_usernames_to_email(apps, schema_editor):
    Profile = apps.get_model("main", "Profile")
    for profile in Profile.objects.all():
        profile.user.username = profile.user.email
        profile.user.save()


class Migration(migrations.Migration):

    dependencies = [("main", "0052_auto_20180912_2128")]

    operations = [migrations.RunPython(set_all_usernames_to_email)]
