# Generated by Django 2.1 on 2018-09-15 06:22

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0053_auto_20180915_0552")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="route",
            field=models.UUIDField(default=uuid.uuid4),
        )
    ]
