# Generated by Django 2.1 on 2018-09-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0054_profile_route")]

    operations = [
        migrations.AlterModelOptions(name="profile", options={"ordering": ["name"]})
    ]
