# Generated by Django 2.1 on 2018-09-15 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0055_auto_20180915_0702")]

    operations = [migrations.RemoveField(model_name="profile", name="route")]
