# Generated by Django 2.1 on 2018-09-15 07:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0056_remove_profile_route")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="route",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        )
    ]
