# Generated by Django 2.1 on 2018-09-15 07:06

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Profile = apps.get_model("main", "Profile")
    for row in Profile.objects.all():
        row.route = uuid.uuid4()
        row.save(update_fields=["route"])


class Migration(migrations.Migration):

    dependencies = [("main", "0057_profile_route")]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
