# Generated by Django 2.1 on 2018-09-15 07:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0058_auto_20180915_0706")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="route",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        )
    ]
