# Generated by Django 2.1.1 on 2018-09-16 06:12

import shortuuid
from django.db import migrations


def increase_resources_route_id(apps, schema_editor):
    Resource = apps.get_model("main", "Resource")
    for resource in Resource.objects.all():
        resource.slug = resource.slug + shortuuid.ShortUUID(
            "abcdefghijkmlnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
        ).random(length=6)
        resource.save()


class Migration(migrations.Migration):

    dependencies = [("main", "0060_resource_lead")]

    operations = [migrations.RunPython(increase_resources_route_id)]
