# Generated by Django 2.1.1 on 2018-09-16 06:18

import shortuuid
from django.db import migrations


def increase_questions_route_id(apps, schema_editor):
    Question = apps.get_model("main", "Question")
    for question in Question.objects.all():
        question.slug = question.slug + shortuuid.ShortUUID(
            "abcdefghijkmlnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
        ).random(length=6)
        question.save()


class Migration(migrations.Migration):

    dependencies = [("main", "0061_auto_20180916_0612")]

    operations = [migrations.RunPython(increase_questions_route_id)]
